In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("datos_limpios.csv")
df.head()

        FECHA PRECIP  EVAP  TMAX TMIN
0  01/01/1961      0  Nulo    25   13
1  02/01/1961      0  Nulo  27.5   14
2  03/01/1961      0  Nulo    31   11
3  04/01/1961      0  Nulo    32   13
4  05/01/1961      0  Nulo    29   14

In [3]:
df = df.replace("Nulo", None)

df["PRECIP"] = pd.to_numeric(df["PRECIP"])
df["EVAP"] = pd.to_numeric(df["EVAP"])
df["TMAX"] = pd.to_numeric(df["TMAX"])
df["TMIN"] = pd.to_numeric(df["TMIN"])

In [4]:
df["PRECIP"] = df["PRECIP"].fillna(df["PRECIP"].mean())
df["EVAP"] = df["EVAP"].fillna(df["EVAP"].mean())
df["TMAX"] = df["TMAX"].fillna(df["TMAX"].mean())
df["TMIN"] = df["TMIN"].fillna(df["TMIN"].mean())

In [5]:
faltantes = df.isnull().sum(axis=1)

df_faltantes = pd.DataFrame()
df_faltantes["FECHA"] = df["FECHA"]
df_faltantes["FALTANTES"] = faltantes

df_faltantes.head()

        FECHA  FALTANTES
0  01/01/1961          0
1  02/01/1961          0
2  03/01/1961          0
3  04/01/1961          0
4  05/01/1961          0

In [7]:
df.head()

        FECHA  PRECIP      EVAP  TMAX  TMIN
0  01/01/1961     0.0  4.882157  25.0  13.0
1  02/01/1961     0.0  4.882157  27.5  14.0
2  03/01/1961     0.0  4.882157  31.0  11.0
3  04/01/1961     0.0  4.882157  32.0  13.0
4  05/01/1961     0.0  4.882157  29.0  14.0